
from enum import Enum

class Commands(str, Enum): 
    ADD_PRODUCT = 'ADD_PRODUCT'
    PATCH_PRODUCT = 'PATCH_PRODUCT'
    REMOVE_PRODUCT = 'REMOVE_PRODUCT'
    ADD_STORAGE = 'ADD_STORAGE'
    PATCH_STORAGE = 'PATCH_STORAGE'
    REMOVE_STORAGE = 'REMOVE_STORAGE'