version: "3"

services:
  postgre:
    image: postgres:15.1-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: numedy_test_task
    volumes:
      - ./pgdata:/var/lib/postgresql
  
  mosquitto:
    image: eclipse-mosquitto:1.5.6
    restart: always
    ports:
      - "1883:1883"
    logging:
      driver: none